version: '3'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./Frontend/ng-importer
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4200:4200"